version: '3.5'
services:
  backend:
    container_name: backend
    build: .
    env_file: ./.env
    environment:
      - API_KEY=$API_KEY
      - API_URL=$API_URL
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    networks:
      - local-network
    depends_on: 
      - redis
    ports:
      - 8080:8000
    restart: always
  redis:
    image: redis:alpine
    volumes:
      - ./redis/data/:/data 
    networks:
      - local-network
  frontend:
    image: tehnarenok/weather-frontend:latest
    ports:
      - 3000:80
    networks:
      - local-network
    restart: always
  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    ports:
      - "${PORT}:80"
    networks:
      - local-network
networks:
  local-network:
    name: local-network
    driver: bridge
